server:
  port: 8004

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tcloud?useUnicode=true&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: 123456
  application:
    name: tcloud-payment-provider
  cloud:
    zookeeper:
      connect-string: 127.0.0.1:2181


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.don.tcloud.providerpayment.entities
